# Copyright (c) 2022-2024 Golioth, Inc.
# SPDX-License-Identifier: Apache-2.0

manifest:
  version: 0.8

  projects:
    - name: zephyr
      revision: v3.6.0
      url: https://github.com/zephyrproject-rtos/zephyr.git
      import:
        path-prefix: deps
        name-allowlist:
          - zephyr
          - cmsis
          - hal_espressif
          - mbedtls
          - mcuboot
          - net-tools
          - segger
          - tfm-mcuboot
          - tinycrypt
          - trusted-firmware-m
          - zcbor
    - name: golioth
      path: modules/lib/golioth-firmware-sdk
      revision: v0.14.0
      url: https://github.com/golioth/golioth-firmware-sdk.git
      submodules: true

  self:
    path: fw
